### PR TITLE
Change border radius and font-size

### PR DESCRIPTION
**Pull request by mllustosa**
Please approve my PR

### CODE REVIEW

**Review by paulaclustosa — CHANGES_REQUESTED** [review]
It's wrong. Remove border radius

**Comment by mllustosa** [comment]
Oops sorry!

**Comment by mllustosa** [comment]
I removed the border radius as requested @paulaclustosa, could you please check again?

**Review by paulaclustosa — APPROVED** [review]
Thanks. Cool

**Pull request merged**
